site_name: wdl-docs
theme:
  name: readthedocs
  include_homepage_in_sidebar: true
  navigation_depth: 4
  highlightjs: true

nav:
  - Home: 'index.md'
  - Getting Started with WDL:
    - 'Base structure': 'WDL/Base_structure.md'
    - 'Add variables': 'WDL/add_variables.md'
    - 'Add plumbing': 'WDL/add_plumbing.md'
    - 'Validate syntax': 'WDL/validate_syntax.md'
    - 'Specify inputs': 'WDL/specify_inputs.md'
    - 'Execute!': 'WDL/execute.md'
    - 'Toolkit: All the tools you need to write and run WDLs': 'WDL/toolkit.md'
  - WDL Plumbing Options:
    - 'Linear chaining': 'WDL/Linear_chaining.md'
    - 'Branch and merge': 'WDL/Branch_and_merge.md'
    - 'Multi-input/Multi-output': 'WDL/MultiInput_MultiOutput.md'
    - 'Scatter-gather parallelism': 'WDL/ScatterGather_parallelism.md'
    - 'Task aliasing': 'WDL/task_aliasing.md'
    - 'Conditional (if/else)': 'WDL/conditionals.md'
  - 'WDL Script Components':
    - 'workflow': 'WDL/workflow.md'
    - 'call': 'WDL/call.md'
    - 'task': 'WDL/task.md'
    - 'command': 'WDL/command.md'
    - 'output': 'WDL/output'
    - 'parameter_meta': 'WDL/parameter_meta.md'
    - 'meta': 'WDL/meta.md'
    - 'basename': 'WDL/basename.md'
    - 'Variable types in WDL': 'WDL/variable_types.md'
  - 'WDL Cookbook':
    - 'Using task outputs downstream': 'WDL/chain_tasks_together.md'
    - 'Building multi-path workflows with conditionals and select_first()': 'WDL/multipath_conditionals.md'
    - 'Running a task with different parameters based on whether on optional input is defined': 'WDL/different_parameters.md'
    - 'Running conditional tasks based on input size': 'WDL/conditionals_input_size.md'
    - 'Running conditional tasks based on optional inputs': 'WDL/conditionals_optional_input.md'
    - 'Conditionally running different WDL tasks based on input data type': 'WDL/conditionals_input_size.md'
    - 'Parallelizing by scattering on an array': 'WDL/scattering_array.md'
    - 'Scattering on an index': 'WDL/scattering_index.md'
    - 'Scattering on optional types': 'WDL/scattering_optional.md'
    - 'Organize multiple inputs using structs': 'WDL/using_structs.md'
  - 'Community':
    - 'Broad Pipeline Development Team': 'community/best_practices_pipelines_team.md'
  - 'Feedback':
    - 'Feedback': 'feedback.md'
